name: Check for words in commit messages

on:
  workflow_dispatch:

jobs:
  Check-commit-message:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check commit message
        run: |
          COMMIT_MSG=$(git log --format=%B -n ${{ github.event.before }}..${{ github.sha }})
          if [[ "$COMMIT_MSG" != *"Finished"* ]]; then
            echo "Commit message should contain 'Finished'."
            echo "COMMIT_MSG=$(git log --format=%B -n ${{ github.event.before }}..${{ github.sha }})"
            echo "[[ "$COMMIT_MSG" != *"Finished"* ]]"
            echo "'$COMMIT_MSG' != *'Finished'*"
            exit 1
          else
            echo "Commit message validation successful."
          fi
