name: Generate commit hashes

on:
  workflow_dispatch:
  
jobs:
  generate-commit-hashes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get commit hashes
        uses: Im-Fran/git-hashes-action@v1.0.3
        id: get_hashes

      - name: Upload commit hashes as artifact
        uses: actions/upload-artifact@v4
        with:
          name: commit-hashes
          path: commit-hashes.txt
        
